### ISSUE TITLE
How to use this tool?

### ISSUE THREAD

**Issue by makc-ar** [JBDCE/grandiaRemasteredRedux#1]
Hi, JBDCE! Step by step how to use this tool? I have a game GRANDIA HD Remaster
I created folders in the С:\Games\GRANDIA HD Remaster\content\content:
C:\Games\GRANDIA HD Remaster\content\TestFileStructure\Output
C:\Games\GRANDIA HD Remaster\content\TestFileStructure\ReduxGameFiles
C:\Games\GRANDIA HD Remaster\content\TestFileStructure\RemasterGameFiles

**Comment by JBDCE** [comment]
Im currently in the process of rewriting the readme file and collecting up a proper release for this. The release should make installing redux a drop in process.

**Comment by JBDCE** [comment]
Hi in case you missed it I have uploaded the release now. You can find it here: https://github.com/JBDCE/grandiaRemasteredRedux/releases

Im still writing up the readme in case you will want to recreate what I have done. As stated before it is not neccessary to recreate my steps if you just care about playing this and the Release should be a simple drop in.

I will close this now. Feel free to open another issue if you encounter any bugs with the game.
