### ISSUE TITLE
The bugs in Gaia 3 crash the game!

### ISSUE THREAD

**Issue by haianh03112001** [JBDCE/grandiaRemasteredRedux#16]
Whenever I enter a fight with the caterpillar looking bugs after a while it crashes the game, I have tried the previous versions but they haven't fixed the problem so far. 
I love what you have been doing with the project keep it up, thanks

**Comment by JBDCE** [comment]
Awesome to see people are using this. 
This bug sounds similar to the Crash described in Issue #11 
Just out of curiosity did you play through the whole game with this redux version?

**Comment by JBDCE** [comment]
Rechecked all the Gaia type enemies. Indeed there are Issues with: Gaia Slug, Gaia Fly Possibly a Gaia Minion? It shouldnt be too dificult to fix but will require some time.
Affected files are M_Dat,bin and strings.txt

**Comment by haianh03112001** [comment]
i did play through the whole game up until that point where it crash

**Comment by JBDCE** [comment]
Its awesome to hear that you played that much of the game!
I have created a little hotfix that should solve the error. Please try it out and tell me if the issue gets resolved. If it does I will create a full release.

[hotfix_issue16.zip](https://github.com/JBDCE/grandiaRemasteredRedux/files/8716232/hotfix_issue16.zip)

If this does not fix your issue please upload your save file. You can find it in %APPDATA%/GRANDIA1/Saves

**Comment by JBDCE** [comment]
Included the Hotfix into the new 0.4.9 release. If anything like this is comming up again please do open up another issue!
