### ISSUE TITLE
Some of the new items in Redux doesn't seem to be in here.

### ISSUE THREAD

**Issue by RegalStar** [JBDCE/grandiaRemasteredRedux#2]
From New parm weapon shop:

On PSX: http://puu.sh/GeJf3/3a31ebff3f.jpg
On PC: http://puu.sh/GeJfF/5d7305487b.jpg

**Comment by RegalStar** [comment]
In fact, a lot of item-related in redux isn't properly reflected here. Coal Candy is stated to give +6 attack in redux but in here it stlil states +2; Poison Bow doesn't seem to actually poison anything, you're supposed to be able to buy resurrect potions in New Parm but they don't show up either, pretty much every "new" item is completely absent, etc.

**Comment by JBDCE** [comment]
Thank you very much for checking this out. I will try to replicate these issues and check what I can do to fix it. 
If I can fix this I will roll out another beta release.
Feel free to report any other issues you find.

**Comment by RegalStar** [comment]
Move/spells seem to have data that aren't changed either. Now that I busted out my old PSX Grandia I realized that Redux changed Rah-Rah Cheer to 16 SP (down from 18), and Burn to 2 MP (up from 1). In this beta the out-of-battle menu have correct cost descriptions, but in-battle the costs are reverted to what they were in vanilla game.

**Comment by JBDCE** [comment]
Alright good news i found the reason why this is broken. Apparently i messed up collecting all the relevant files and missed important files that are related to the actual battle scenes. I will provide a new release in a few hours.

**Comment by JBDCE** [comment]
Just published the new release. I hope this fixes most of the issues you mentioned. Some stuff still needs more work. I outlined the details in the release: 
https://github.com/JBDCE/grandiaRemasteredRedux/releases/tag/0.4.1-beta
