### ISSUE TITLE
Game Freezing - Random Text Block Letters

### ISSUE THREAD

**Issue by Gavolash** [JBDCE/grandiaRemasteredRedux#3]
Hey there,

Was super keen for this, dropped in the release files into my existing game, currently escaping the Garlyle bass.

Not sure if it's cause I've already playing through the game on an existing save or if it's an issue with this Redux, but while walking around, the text block pops up randomly with random character text in it like ?0@?s?20aa`1~! or ".... must capture him..." but not spoken by anyone, just pops up. 

The game then basically freezes completely. Sometimes it happens if I talk to a soldier. 

I assume a new game from scratch is probably the best for this?

Thanks for the awesome work!

**Comment by Gavolash** [comment]
Just adding in here. 

Started a new game save and Save Point at Mana Road doesn't have a Recover option or quit, I have to go into Save game and then exit out to be able to continue, is this by design from Redux?

**Comment by JBDCE** [comment]
Thank you for trying it out. On regard to the Garlyle Base issues it might very well redux at fault for this. Garlyle Base in Particular is a difficult Area to troubleshoot from the Debug Menue so if you could it would be awesome if you could link me your Save Game. Im assuming you are running the more recent 0.4.1 Release?
On behalf of the Save Point in Mana Road this was indeed an original Redux design. It is set like that so that you cannot just recover after every battle. This appears numerous times throughout Redux.

**Comment by Gavolash** [comment]
[Saves.zip](https://github.com/JBDCE/grandiaRemasteredRedux/files/5081351/Saves.zip)

Hey bud, thanks for the quick response. Added the saves here as I wasn't sure where else. 

There's currently 2 saves there, 1st one is before you fight Seg Saki. 2nd save is after defeating her.

2nd one seems to be where the issue is happening (or at least see the issue described as you're not locked in combat with Saki), Just run around and the text may randomly pop up/then freeze/crash or go find some soldiers in the base and talk to them with the same result. 

I am indeed using the files from 0.4.1. 

Guess Redux is harder than I thought haha as I started a new game and it's defs a lot tougher.

**Comment by Gavolash** [comment]
Hey @JBDCE got some more to report,

I started the game from scratch, grinded it out up until the same spot it was breaking above, I beat Saki and the game proceeded to break again with the same/similar issues as originally reported.

So it doesn't look to be an issue with loading the mod onto an existing saved game, see attached image of game frozen in the Garyle base.

Game proceeded to freeze with the below, this time caught an image of it.

![Broken](https://user-images.githubusercontent.com/69740952/90754920-ded0bd00-e31d-11ea-950e-4e1552d056c6.jpg)

**Comment by JBDCE** [comment]
Well a problem like that shows how unstable all this still is as I still not really know what im doing. Thank you very much regardless for your commitment to this. Right now i would suggest you try to revert the Redux mod and just continue the save file until after you leave the base. Maybe it gets better aftewards and that is just some wierd edge case but I highly doubt that to be the case.
To me this looks like the game is trying to render Text that it is unable to find in memory... Probably an issue inside of the corresponding FIELD/****.mdp file...
Again thank you very much for your help in documenting issues like that I will try my best to figure out why this happens.

**Comment by Gavolash** [comment]
Just an update here.

Switched back to my non Redux mod and got passed Garyle Base and saved, switched back to the Redux and haven't had an issues past Luc Village so far.

No idea if it's an actual Remaster bug or Redux but so far so good past Garyle.

**Comment by JBDCE** [comment]
should be fixed with the latest release
