### ISSUE TITLE
Gargoyle elite troops in DOOM tower cause crashes

### ISSUE THREAD

**Issue by haianh03112001** [JBDCE/grandiaRemasteredRedux#6]
So far the game have been working fine but when i start to engage the elite troop in the doom tower in battle the game crashes every time.

**Comment by JBDCE** [comment]
Game crashes when trying to select them by the player. Likely mixup inside M_DAT.BIN
Needs fixing ASAP

**Comment by JBDCE** [comment]
Indeed the issue was with the Power Cut ability not beeing corectly renamed. Similar to #11 Will get fixed in 0.4.6
