### ISSUE TITLE
Softlocked in Garlyle base

### ISSUE THREAD

**Issue by Renyth** [JBDCE/grandiaRemasteredRedux#7]
Can fight Saki infinitely over and over but not Nana or Mio at all, tried all sorts of methods to change triggers, softlocks when talking to any soldiers since the fights don't trigger after getting the key off saki, no train cutscene plays so stuck forever, no earlier save to load sadly.

**Comment by Renyth** [comment]
Just checked another thread apparently this is a thing, I do remember Garlyle base being abit of a mess years ago playing the mod so I'll try unmodding then remodding it after the base. cheers.

**Comment by JBDCE** [comment]
this got fixed in the latest release
